server:
  port: 9090

spring:
  application:
    name: api-gateway10

  cloud:
    gateway:
      routes:

        - id: appointment-service
          uri: lb://APPOINTMENT-SERVICE10
          predicates:
            - Path=/appointments/**

        - id: doctor-service
          uri: lb://DOCTOR-SERVICE10
          predicates:
            - Path=/doctors/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
