# server:
#   port: 9090

# spring:
#   cloud:
#     gateway:
#       routes:

#         - id: appointment-service
#           uri: lb://APPOINTMENT-SERVICE10
#           predicates:
#             - Path=/doctors,/doctors/**

#             # - Path=/appointments/**

#         - id: doctor-service
#           uri: lb://DOCTOR-SERVICE10
#           predicates:
#             - Path=/doctors,/doctors/**

#             # - Path=/doctors/**


# # eureka:
# #   client:
# #     service-url:
# #       defaultZone: http://localhost:8761/eureka
# #   instance:
# #     prefer-ip-address: true
# #     hostname: 127.0.0.1
# # management:
# #   tracing:
# #     sampling:
# #       probability: 1.0

# #   endpoints:
# #     web:
# #       exposure:
# #         include: "*"
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka
# server:
#   port: 9090

# spring:
#   application:
#     name: api-gateway10

#   cloud:
#     gateway:
#       routes:

#         - id: doctor-service
#           uri: lb://DOCTOR-SERVICE10
#           predicates:
#             - Path=/doctors/**

#         - id: appointment-service
#           uri: lb://APPOINTMENT-SERVICE10
#           predicates:
#             - Path=/appointments/**

# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"

#   endpoint:
#     gateway:
#       access: unrestricted













spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: doctor-service
              uri: lb://DOCTOR-SERVICE
              predicates:
                # - Path=/doctors/**
                - Path=/doctors,/doctors/**
            - id: appointment-service
              uri: lb://APPOINTMENT-SERVICE
              predicates:
                # - Path=/appointment/**
                - Path=/appointments,/appointments/**

server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: 127.0.0.1
management:
  tracing:
    sampling:
      probability: 1.0

  endpoints:
    web:
      exposure:
        include: "*"




















