
server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appointment_db10
    username: root
    password: Adi@2552

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
