spring:

  datasource:
    url: jdbc:mysql://localhost:3306/appointment_db10
    username: root
    password: Adi@2552
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
